
version: '3'
services:
  jes-match-service:
    container_name: jes-match-service
    build: ./app
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    links:
      - jes-match-mongo
    environment:
      PORT: $PORT
      MONGO_URL: $MONGO_URL

  jes-match-mongo:
    container_name: jes-match-mongo
    image: mongo
    restart: unless-stopped
    ports:
      - $MONGO_PORT:27017
